var links = [
  {source: nodes[1], target: nodes[9], type: 0},
  {source: nodes[8], target: nodes[2], type: 0},
  {source: nodes[2], target: nodes[12], type: 1},
  {source: nodes[9], target: nodes[5], type: 1},
  {source: nodes[3], target: nodes[7], type: 0},
  {source: nodes[10], target: nodes[0], type: 0},
  {source: nodes[3], target: nodes[11], type: 0},
  {source: nodes[10], target: nodes[4], type: 0},
  {source: nodes[4], target: nodes[8], type: 0},
  {source: nodes[11], target: nodes[1], type: 0},
  {source: nodes[2], target: nodes[7], type: 0},
  {source: nodes[9], target: nodes[0], type: 0},
  {source: nodes[5], target: nodes[7], type: 1},
  {source: nodes[12], target: nodes[0], type: 1},
  {source: nodes[0], target: nodes[13], type: 1},
  {source: nodes[7], target: nodes[6], type: 1},
  {source: nodes[1], target: nodes[13], type: 1},
  {source: nodes[8], target: nodes[6], type: 1},
  {source: nodes[1], target: nodes[12], type: 1},
  {source: nodes[8], target: nodes[5], type: 1},
];